
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import create_razorpay_order

urlpatterns = [
    path('home/', views.home, name='home'),
    path('register/', views.registerPage, name='register'),
    path('menu/', views.menu, name='menu'),
    path('menu!/', views.menu_not_user, name='menu!'),
    path('orders/', views.orders, name='orders'),
    path('account/', views.account, name='account'),
    path('cart/', views.cart, name='cart'),
    
    path('cart/remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('cart/remove_product/<int:product_id>', views.cart_remove_product, name='cart_remove_product'),    
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('menu/breakfast', views.breakfast, name='breakfast'),
    path('menu/lunch', views.lunch, name='lunch'),
    path('menu/dinner', views.dinner, name='dinner'),
    path('search/', views.search, name='search'),
    path('create-subscription/', views.create_subscription, name='create_subscription'),
    path('view-subscriptions/', views.view_subscriptions, name='view_subscriptions'),
    path('view-subscriptions/<int:subscription_id>/payment/', views.process_payment, name='process_payment'),
    # path('cart_payments/<int:cart_id>/', views.create_cart_payment, name='create_cart_payment'),
    path('complete_payment/', views.complete_payment, name='complete_payment'),
    path('user/cart_orders/', views.user_cart_orders, name='user_cart_orders'),  # Add this line
    path('update-address/', views.update_address, name='update_address'),
    path('contact_us/',views.contact_us,name='contact_us'),
    path('adminhome/', views.adminhome, name='adminhome'),
    path('admin_cartpayments/', views.admin_cartpayments, name='admin_cartpayments'),
    path('add_food/', views.add_food, name='add_food'),
    path('all_subscriptions/', views.all_subscriptions, name='all_subscriptions'),
    path('admin_payment/',views.admin_payment, name='admin_payment'),
    path('admin_contact/',views.admin_contact, name='admin_contact'),
    path('download/users-report/', views.download_users_pdf, name='download_users_pdf'),
    path('cart_payments_pdf/', views.cart_payment_pdf, name='cart_payment_pdf'),
    path('subscription_report_pdf/',views.subscription_report_pdf, name='subscription_report_pdf'),
    path('cartpayments_pdf/', views.cartpayments_report_pdf, name='cartpayments_report_pdf'),
    path('contact_report_pdf/',views.contact_report_pdf, name='contact_report_pdf'),
    path('admin_login/',views.admin_login, name='admin_login'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('reset-password/<int:user_id>/', views.reset_password_view, name='reset_password'),

    path('store-admins/', views.storeadmin_list, name='storeadmin_list'),

    path('add-storeadmin/', views.add_storeadmin_backend, name='add_storeadmin_backend'),
    path('add_restaurant/', views.add_restaurant, name='add_restaurant'),
    path('restaurant_home/', views.restaurant_home, name='restaurant_home'),
    path('restaurant_update_profile/',views.restaurant_update_profile, name='restaurant_update_profile'),
    path('restaurant_menu/', views.restaurant_menu, name='restaurant_menu'),
    path('resturent_track_order/',views.resturent_track_order, name='resturent_track_order'),
    path('restaurant_earnings/',views.restaurant_earnings, name='restaurant_earnings'),
    path('', views.landing_page, name='landing_page'),
    path('delivery_register/',views.delivery_register, name='delivery_register'),
    path('delivery_agentstep1/',views.delivery_agentstep1, name='delivery_agentstep1'),
    path('delivery_agentstep2/',views.delivery_agentstep2, name='delivery_agentstep2'),
    path('delivery_dashboard/', views.delivery_dashboard, name='delivery_dashboard'),
   
    path('delivery_myearnings/', views.delivery_myearnings, name='delivery_myearnings'),
    path('delivery_myorders/', views.delivery_myorders, name='delivery_myorders'),
    path('delivery_profile/', views.delivery_profile, name='delivery_profile'),
    path('add_to_cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('save_weekly_menu/', views.save_weekly_menu, name='save_weekly_menu'),
    path('menu/delete/<int:item_id>/', views.delete_menu_item, name='delete_menu_item'),
    path('api/save-weekly-meal/', views.save_weekly_meal, name='save_weekly_meal'),
    path('preorder/', views.preorder, name='preorder'),
    path('customize/<int:meal_id>/', views.customize_meal, name='customize_meal'),
    path('my_custom_plans/', views.my_custom_plans, name='my_custom_plans'),
    path('delete-custom-plan/<int:plan_id>/', views.delete_custom_plan, name='delete_custom_plan'),
    path('add_curry/', views.add_curry, name='add_curry'),
    path('delete-curry/<int:curry_id>/', views.delete_curry_item, name='delete_curry_item'),
    path('order_lunch/', views.order_lunch_box, name='order_lunch'),
    path('skip_meal/', views.skip_meal, name='skip_meal'),
    path('pay_now/',views. pay_now, name='pay_now'),
    path('create_razorpay_order/', views.create_razorpay_order, name='create_razorpay_order'),
    path("razorpay_success/",views.razorpay_success, name="razorpay_success"),
    path('thank_you/', views.thank_you, name='thank_you'),
    path("save_delivery_address/", views.save_delivery_address, name="save_delivery_address"),
    path('custom-plan/initiate-payment/', views.initiate_custom_plan_payment, name='initiate_custom_plan_payment'),
    path('custom-plan/payment-success/', views.custom_plan_payment_success, name='custom_plan_payment_success'),
    path('payment-success1/', views.payment_success1, name='payment_success1'),
    path('edit-meal/', views.edit_meal, name='edit_meal'),
    path('get-meal-items/', views.get_items_by_meal_type, name='get_meal_items'),

    path('storeadmin/approve/<int:pk>/', views.approve_storeadmin, name='approve_storeadmin'),
    path('storeadmin/deactivate/<int:pk>/', views.deactivate_storeadmin, name='deactivate_storeadmin'),
    path('storeadmin/remove/<int:pk>/', views.remove_storeadmin, name='remove_storeadmin'),
    path('send_otp/', views.send_otp, name='send_otp'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('order/<str:order_type>/<int:order_id>/details/', views.view_order_details, name='view_order_details'),
    path('manage-stores/', views.manage_stores, name='manage_stores'),
    path('add-store/', views.add_store_location, name='add_store_location'),
    path('edit-store/<int:store_id>/', views.edit_store_location, name='edit_store_location'),
    path('delete-store/<int:store_id>/', views.delete_store_location, name='delete_store_location'),
    path('api/today-meals/',views.today_meals_api, name='today-meals'),
    path('today-orders/', views.today_orders_api_template, name='today-orders'),  
    path('api/update-status/',views.update_order_status, name='update_order_status'),
    path('api/live-summary/',views.live_summary, name='live_summary'),
]
