# Generated by Django 5.1.1 on 2024-10-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0003_alter_food_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='users',
            new_name='user',
        ),
    ]
