# Generated by Django 5.1.1 on 2024-10-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0004_rename_users_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='items',
            new_name='food_items',
        ),
    ]
