# Generated by Django 5.1.1 on 2024-10-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0007_alter_payment_card_number_alter_payment_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expiry_date',
        ),
    ]
