# Generated by Django 5.1.1 on 2024-10-01 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0010_alter_food_image_alter_payment_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='food_images/'),
            preserve_default=False,
        ),
    ]
