# Generated by Django 5.1.1 on 2024-10-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0012_alter_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='food_items',
        ),
        migrations.AddField(
            model_name='subscription',
            name='breakfast_items',
            field=models.ManyToManyField(blank=True, related_name='breakfast_subscriptions', to='NO_KITCHEN_APP.food'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dinner_items',
            field=models.ManyToManyField(blank=True, related_name='dinner_subscriptions', to='NO_KITCHEN_APP.food'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lunch_items',
            field=models.ManyToManyField(blank=True, related_name='lunch_subscriptions', to='NO_KITCHEN_APP.food'),
        ),
    ]
