# Generated by Django 5.1.1 on 2024-10-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0017_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='payment_status',
            field=models.CharField(default='Completed', max_length=20),
        ),
    ]
