# Generated by Django 5.1.1 on 2024-10-07 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0018_alter_cartpayment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpayment',
            name='cart',
            field=models.ForeignKey(null=True, to='NO_KITCHEN_APP.Cart', on_delete=models.CASCADE),
            preserve_default=False,
        ),
    ]
