# Generated by Django 5.1.1 on 2024-10-07 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0019_cartpayment_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NO_KITCHEN_APP.subscription'),
        ),
    ]
