# Generated by Django 5.1.1 on 2024-10-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0025_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartpayment',
            name='cart_items',
            field=models.ManyToManyField(blank=True, to='NO_KITCHEN_APP.cartitem'),
        ),
    ]
