# Generated by Django 5.1.1 on 2024-10-08 05:41

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0026_alter_cartitem_price_alter_cartpayment_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpayment',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartpayment',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
