# Generated by Django 5.1.1 on 2024-10-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0027_cartpayment_address_cartpayment_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='address',
            field=models.CharField(max_length=550),
        ),
    ]
