# Generated by Django 5.1.1 on 2024-10-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0028_alter_cartpayment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
