# Generated by Django 5.1.1 on 2024-10-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0029_alter_cartpayment_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
