# Generated by Django 5.1.1 on 2024-10-08 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0030_alter_cartpayment_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpayment',
            name='unique_cart_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
