# Generated by Django 5.1.1 on 2024-10-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0032_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
