# Generated by Django 5.1.1 on 2024-10-10 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0037_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
