# Generated by Django 5.1 on 2025-06-18 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0040_nokitchenmenu_stock_nokitchencart_nokitchencartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoKitchenSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_items', models.ManyToManyField(to='NO_KITCHEN_APP.nokitchenmenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMenuPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('rotation_number', models.PositiveSmallIntegerField(default=1, help_text='1, 2 or 3 to allow 3 sets of menus')),
                ('breakfast_items', models.ManyToManyField(limit_choices_to={'meal_type': 'breakfast'}, related_name='breakfast_rotations', to='NO_KITCHEN_APP.nokitchenmenu')),
                ('dinner_items', models.ManyToManyField(limit_choices_to={'meal_type': 'dinner'}, related_name='dinner_rotations', to='NO_KITCHEN_APP.nokitchenmenu')),
                ('lunch_items', models.ManyToManyField(limit_choices_to={'meal_type': 'lunch'}, related_name='lunch_rotations', to='NO_KITCHEN_APP.nokitchenmenu')),
            ],
            options={
                'unique_together': {('day', 'rotation_number')},
            },
        ),
    ]
