# Generated by Django 5.1 on 2025-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0041_nokitchensubscription_weeklymenuplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMealSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snacks'), ('dessert', 'Desserts'), ('special', 'Special Package / Event')], max_length=10)),
                ('selected_items', models.ManyToManyField(to='NO_KITCHEN_APP.nokitchenmenu')),
            ],
        ),
    ]
