# Generated by Django 5.1 on 2025-06-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0043_weeklymealselection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymealselection',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10),
        ),
    ]
