# Generated by Django 5.1 on 2025-06-24 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0045_custommealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommealplan',
            name='custom_items',
        ),
        migrations.CreateModel(
            name='CustomMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NO_KITCHEN_APP.nokitchenmenu')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='NO_KITCHEN_APP.custommealplan')),
            ],
        ),
    ]
