# Generated by Django 5.1 on 2025-06-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0046_remove_custommealplan_custom_items_custommealitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoKitchenCurries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curry_type', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], max_length=10)),
                ('curry_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curries', to='NO_KITCHEN_APP.nokitchenmenu')),
            ],
        ),
    ]
