# Generated by Django 5.1 on 2025-06-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0047_nokitchencurries'),
    ]

    operations = [
        migrations.AddField(
            model_name='nokitchencurries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='curry_images/'),
        ),
        migrations.AddField(
            model_name='nokitchencurries',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
