# Generated by Django 5.1 on 2025-06-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0048_nokitchencurries_image_nokitchencurries_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nokitchencurries',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curries', to='NO_KITCHEN_APP.nokitchenmenu'),
        ),
        migrations.AlterField(
            model_name='nokitchencurries',
            name='quantity',
            field=models.CharField(default='1 Bowl', max_length=50),
        ),
    ]
