# Generated by Django 5.1 on 2025-07-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0049_alter_nokitchencurries_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommealitem',
            name='item',
        ),
        migrations.AddField(
            model_name='custommealitem',
            name='curry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NO_KITCHEN_APP.nokitchencurries'),
        ),
        migrations.CreateModel(
            name='MealCustomizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NO_KITCHEN_APP.nokitchenmenu')),
            ],
        ),
        migrations.AlterField(
            model_name='custommealitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NO_KITCHEN_APP.mealcustomizationplan'),
        ),
    ]
