# Generated by Django 5.1 on 2025-07-02 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0050_remove_custommealitem_item_custommealitem_curry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommealitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='NO_KITCHEN_APP.custommealplan'),
        ),
        migrations.RemoveField(
            model_name='custommealitem',
            name='curry',
        ),
        migrations.AddField(
            model_name='custommealitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NO_KITCHEN_APP.nokitchenmenu'),
        ),
        migrations.AddField(
            model_name='custommealplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custommealplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MealCustomizationPlan',
        ),
    ]
