# Generated by Django 5.1 on 2025-07-02 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0051_alter_custommealitem_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCurryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('curry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NO_KITCHEN_APP.nokitchencurries')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curry_items', to='NO_KITCHEN_APP.custommealplan')),
            ],
        ),
    ]
