# Generated by Django 5.1 on 2025-07-02 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0052_customcurryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('meal_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='NO_KITCHEN_APP.weeklymealselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
