# Generated by Django 5.1 on 2025-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0054_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymealselection',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklymealselection',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
