# Generated by Django 5.1 on 2025-07-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0055_weeklymealselection_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymealselection',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
