# Generated by Django 5.1 on 2025-07-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0056_weeklymealselection_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymenuplan',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklymenuplan',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklymenuplan',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
