# Generated by Django 5.1 on 2025-07-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0059_deliveryaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='address_type',
            new_name='breakfast_address_type',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='preferred_time',
            new_name='breakfast_time',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='dinner_address_type',
            field=models.CharField(default='Home', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='dinner_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='lunch_address_type',
            field=models.CharField(default='Home', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='lunch_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
