# Generated by Django 5.1 on 2025-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0060_rename_address_type_deliveryaddress_breakfast_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='breakfast_address_type',
            field=models.CharField(blank=True, default='Home', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='dinner_address_type',
            field=models.CharField(blank=True, default='Home', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='lunch_address_type',
            field=models.CharField(blank=True, default='Home', max_length=20, null=True),
        ),
    ]
