# Generated by Django 5.1 on 2025-07-12 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0063_custommealplan_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalMealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('flat_number', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('breakfast_time', models.CharField(blank=True, max_length=50, null=True)),
                ('lunch_time', models.CharField(blank=True, max_length=50, null=True)),
                ('dinner_time', models.CharField(blank=True, max_length=50, null=True)),
                ('breakfast_address_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lunch_address_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dinner_address_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ordered_items', models.TextField(help_text='Store JSON or comma-separated meal items')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
