# Generated by Django 5.1 on 2025-07-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0064_finalmealorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmealorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='finalmealorder',
            name='ordered_items',
            field=models.TextField(help_text='Comma-separated or JSON string of meal items'),
        ),
    ]
