# Generated by Django 5.1 on 2025-07-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0067_storeadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommealplan',
            name='custom_order_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
