# Generated by Django 5.1 on 2025-07-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0068_custommealplan_custom_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommealplan',
            name='breakfast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custommealplan',
            name='dinner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custommealplan',
            name='lunch',
            field=models.TextField(blank=True, null=True),
        ),
    ]
