# Generated by Django 5.1 on 2025-07-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0069_custommealplan_breakfast_custommealplan_dinner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommealplan',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
