# Generated by Django 5.1 on 2025-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0070_custommealplan_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommealplan',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
