# Generated by Django 5.1 on 2025-07-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0071_custommealplan_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymealselection',
            name='custom_order_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
