# Generated by Django 5.1 on 2025-07-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0072_weeklymealselection_custom_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymenuplan',
            name='plan_order_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
