# Generated by Django 5.1 on 2025-07-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0073_weeklymenuplan_plan_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='address_type',
            field=models.CharField(blank=True, default='Home', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
