# Generated by Django 5.1 on 2025-07-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0074_deliveryaddress_address_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_card_image', models.ImageField(blank=True, null=True, upload_to='delivery_docs/')),
                ('aadhar_number', models.CharField(max_length=12)),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='delivery_docs/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='delivery_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
