# Generated by Django 5.1 on 2025-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0078_preparationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationstatus',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
