# Generated by Django 5.1 on 2025-08-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0079_alter_preparationstatus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='agent_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
