# Generated by Django 5.1 on 2025-08-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0081_detectedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
