# Generated by Django 5.1 on 2025-08-08 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0082_storelocation_city_storelocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='selected_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NO_KITCHEN_APP.storelocation'),
        ),
    ]
