# Generated by Django 5.1 on 2025-08-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0083_deliverypartner_selected_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeadmin',
            name='store',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='NO_KITCHEN_APP.storelocation'),
        ),
    ]
