# Generated by Django 5.1 on 2025-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0084_storeadmin_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nokitchenmenu',
            name='stock',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
