# Generated by Django 5.1 on 2025-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0087_orderassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='order_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
