# Generated by Django 5.1 on 2025-10-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0088_orderassignment_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='NO_KITCHEN_APP.deliverypartner'),
        ),
    ]
