# Generated by Django 5.1 on 2025-10-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0089_alter_orderassignment_delivery_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
