# Generated by Django 5.1 on 2025-10-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0090_deliverypartner_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to Partner'), ('picked_up', 'Picked Up'), ('on_the_way', 'On The Way'), ('reached', 'Reached Customer'), ('delivered', 'Delivered'), ('failed', 'Failed Delivery')], default='pending', max_length=20),
        ),
    ]
