# Generated by Django 5.1 on 2025-10-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0091_alter_orderassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='live_status',
            field=models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to Partner'), ('picked_up', 'Picked Up'), ('on_the_way', 'On The Way'), ('reached', 'Reached Customer'), ('delivered', 'Delivered'), ('failed', 'Failed Delivery')], default='assigned', max_length=20),
        ),
    ]
