# Generated by Django 5.1 on 2025-10-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0092_orderassignment_live_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='delivery_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_photos/'),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='pickup_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_photos/'),
        ),
    ]
