# Generated by Django 5.1 on 2025-10-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NO_KITCHEN_APP', '0093_orderassignment_delivery_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderassignment',
            table='NO_KITCHEN_APP_orderassignment',
        ),
    ]
